# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mapper.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cmapper.proto\"(\n\rMapperRequest\x12\x17\n\x0fpartition_index\x18\x01 \x01(\x05\"\x1d\n\x05Point\x12\t\n\x01x\x18\x01 \x01(\x01\x12\t\n\x01y\x18\x02 \x01(\x01\"A\n\nMapperItem\x12\r\n\x05index\x18\x01 \x01(\x05\x12\x15\n\x05point\x18\x02 \x01(\x0b\x32\x06.Point\x12\r\n\x05\x63ount\x18\x03 \x01(\x05\",\n\x0eMapperResponse\x12\x1a\n\x05items\x18\x01 \x03(\x0b\x32\x0b.MapperItem2;\n\x06Mapper\x12\x31\n\x0cGetPartition\x12\x0e.MapperRequest\x1a\x0f.MapperResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'mapper_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_MAPPERREQUEST']._serialized_start=16
  _globals['_MAPPERREQUEST']._serialized_end=56
  _globals['_POINT']._serialized_start=58
  _globals['_POINT']._serialized_end=87
  _globals['_MAPPERITEM']._serialized_start=89
  _globals['_MAPPERITEM']._serialized_end=154
  _globals['_MAPPERRESPONSE']._serialized_start=156
  _globals['_MAPPERRESPONSE']._serialized_end=200
  _globals['_MAPPER']._serialized_start=202
  _globals['_MAPPER']._serialized_end=261
# @@protoc_insertion_point(module_scope)
