# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: master.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cmaster.proto\x12\x06master\"\x0c\n\nifComplete\"$\n\x06status\x12\x0e\n\x06ifDone\x18\x01 \x01(\x08\x12\n\n\x02id\x18\x02 \x01(\x03\x32\x46\n\x0eMasterServicer\x12\x34\n\x0cworkComplete\x12\x12.master.ifComplete\x1a\x0e.master.status\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'master_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_IFCOMPLETE']._serialized_start=24
  _globals['_IFCOMPLETE']._serialized_end=36
  _globals['_STATUS']._serialized_start=38
  _globals['_STATUS']._serialized_end=74
  _globals['_MASTERSERVICER']._serialized_start=76
  _globals['_MASTERSERVICER']._serialized_end=146
# @@protoc_insertion_point(module_scope)
