# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: master.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cmaster.proto\x12\x06master\"\"\n\rMapperRequest\x12\x11\n\tinputData\x18\x01 \x01(\t\":\n\x0eMapperResponse\x12\x18\n\x10intermediateData\x18\x01 \x01(\t\x12\x0e\n\x06status\x18\x02 \x01(\x08\"*\n\x0eReducerRequest\x12\x18\n\x10intermediateData\x18\x01 \x01(\t\"1\n\x0fReducerResponse\x12\x0e\n\x06output\x18\x01 \x01(\t\x12\x0e\n\x06status\x18\x02 \x01(\x08\x32R\n\x06Mapper\x12H\n\x15GetIntermediateOutput\x12\x15.master.MapperRequest\x1a\x16.master.MapperResponse\"\x00\x32I\n\x07Reducer\x12>\n\tGetResult\x12\x16.master.ReducerRequest\x1a\x17.master.ReducerResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'master_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_MAPPERREQUEST']._serialized_start=24
  _globals['_MAPPERREQUEST']._serialized_end=58
  _globals['_MAPPERRESPONSE']._serialized_start=60
  _globals['_MAPPERRESPONSE']._serialized_end=118
  _globals['_REDUCERREQUEST']._serialized_start=120
  _globals['_REDUCERREQUEST']._serialized_end=162
  _globals['_REDUCERRESPONSE']._serialized_start=164
  _globals['_REDUCERRESPONSE']._serialized_end=213
  _globals['_MAPPER']._serialized_start=215
  _globals['_MAPPER']._serialized_end=297
  _globals['_REDUCER']._serialized_start=299
  _globals['_REDUCER']._serialized_end=372
# @@protoc_insertion_point(module_scope)
