# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import master_pb2 as master__pb2


class MasterServicerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.workCompleteReducer = channel.unary_unary(
                '/master.MasterServicer/workCompleteReducer',
                request_serializer=master__pb2.ifComplete.SerializeToString,
                response_deserializer=master__pb2.status.FromString,
                )
        self.workCompleteMapper = channel.unary_unary(
                '/master.MasterServicer/workCompleteMapper',
                request_serializer=master__pb2.ifComplete.SerializeToString,
                response_deserializer=master__pb2.status.FromString,
                )


class MasterServicerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def workCompleteReducer(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def workCompleteMapper(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MasterServicerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'workCompleteReducer': grpc.unary_unary_rpc_method_handler(
                    servicer.workCompleteReducer,
                    request_deserializer=master__pb2.ifComplete.FromString,
                    response_serializer=master__pb2.status.SerializeToString,
            ),
            'workCompleteMapper': grpc.unary_unary_rpc_method_handler(
                    servicer.workCompleteMapper,
                    request_deserializer=master__pb2.ifComplete.FromString,
                    response_serializer=master__pb2.status.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'master.MasterServicer', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class MasterServicer(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def workCompleteReducer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/master.MasterServicer/workCompleteReducer',
            master__pb2.ifComplete.SerializeToString,
            master__pb2.status.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def workCompleteMapper(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/master.MasterServicer/workCompleteMapper',
            master__pb2.ifComplete.SerializeToString,
            master__pb2.status.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
